# Calls a workflow that builds an alpha release.

name: Build Alpha

on:
  push:
    tags:
      - '10.*.*-alpha*'
      - '10.*.*-Alpha*'
    paths-ignore:
      - '.github/**'

jobs:
  package:
    name: Package Alpha
    uses: SFX-WoW/shared/.github/workflows/build-alpha.yml@main
